// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCp8nk6PyVbES_jYbb3IklTid0qUK09vMI',
    appId: '1:1067251155748:web:171ddb1b3aab8e67c6e9b1',
    messagingSenderId: '1067251155748',
    projectId: 'employee-db-f2d66',
    authDomain: 'employee-db-f2d66.firebaseapp.com',
    storageBucket: 'employee-db-f2d66.appspot.com',
    measurementId: 'G-2BLJZ0GG98',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZhBB9jf1OFBQ1YAuNQnmjOh1O9EWe4SA',
    appId: '1:1067251155748:android:80ab2e8989e1d576c6e9b1',
    messagingSenderId: '1067251155748',
    projectId: 'employee-db-f2d66',
    storageBucket: 'employee-db-f2d66.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTOk6MpX-BfUhQiEbRrz7bOyyfuLEDIbw',
    appId: '1:1067251155748:ios:4f30de555b6e2646c6e9b1',
    messagingSenderId: '1067251155748',
    projectId: 'employee-db-f2d66',
    storageBucket: 'employee-db-f2d66.appspot.com',
    iosBundleId: 'com.example.employee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTOk6MpX-BfUhQiEbRrz7bOyyfuLEDIbw',
    appId: '1:1067251155748:ios:4f30de555b6e2646c6e9b1',
    messagingSenderId: '1067251155748',
    projectId: 'employee-db-f2d66',
    storageBucket: 'employee-db-f2d66.appspot.com',
    iosBundleId: 'com.example.employee',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCp8nk6PyVbES_jYbb3IklTid0qUK09vMI',
    appId: '1:1067251155748:web:7bb1426f98537f8bc6e9b1',
    messagingSenderId: '1067251155748',
    projectId: 'employee-db-f2d66',
    authDomain: 'employee-db-f2d66.firebaseapp.com',
    storageBucket: 'employee-db-f2d66.appspot.com',
    measurementId: 'G-JS7R1P59QF',
  );
}
